name: Export OpenTelemetry Trace for CI

on:
  workflow_run:
    workflows:
      - Smoke tests
    types: [completed]

permissions:
  contents: read # To access the private repository
  actions: read # To read workflow runs
  pull-requests: read # To read PR labels
  checks: read # Optional. To read run annotations

jobs:
  otel-export-trace:
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    steps:
      - name: Export Workflow Trace (staging)
        uses: corentinmusard/otel-cicd-action@v4
        with:
          otlpEndpoint: https://otel.staging.climatepolicyradar.org/v1/traces
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
          otlpHeaders: false
          otelServiceName: navigator-frontend-smoke-tests
          extraAttributes: environment=staging
