name: Send slack message on deployment
on: deployment

permissions:
  id-token: write
  contents: read

jobs:
  send-slack-message-staging-updates:
    runs-on: ubuntu-latest
    steps:
      # we can't use the github.event.deployment.environment directly in the environment property
      # so we need to switch on this case to get the secret.
      - id: webhook_url
        run: |
          if [ "${{ github.event.deployment.environment }}" = "staging" ]; then
            echo "webhook_url=${{ secrets.SLACK_WEBHOOK_URL_STAGING_UPDATES_CHANNEL }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.deployment.environment }}" = "production" ]; then
            echo "webhook_url=${{ secrets.SLACK_WEBHOOK_URL_PRODUCTION_UPDATES_CHANNEL }}" >> $GITHUB_OUTPUT
          fi
      - id: pr_number
        run: |
          PR_NUMBER=$(gh pr list --search "$(git rev-parse HEAD)" --state all --json number -q '.[0].number')
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ steps.webhook_url.outputs.webhook_url }}
          webhook-type: incoming-webhook
          payload: |
            ðŸš€ Deploying ${{ github.repository }} to ${{ github.event.deployment.environment }}
            â€¢ *PR*: https://github.com/${{ github.repository }}/pulls/${{ steps.pr_number.outputs.pr_number }}
